// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvL7OJod-VXWV3fc1agSWslQzHMKjB6U',
    appId: '1:216387410941:android:2ab88bf4fcbe76f9539794',
    messagingSenderId: '216387410941',
    projectId: 'shopreal-71605',
    storageBucket: 'shopreal-71605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjXNlTs3tATdAFZFGnJyuj5vufmog-AA',
    appId: '1:216387410941:ios:6e19045fdfd12ea4539794',
    messagingSenderId: '216387410941',
    projectId: 'shopreal-71605',
    storageBucket: 'shopreal-71605.firebasestorage.app',
    androidClientId: '216387410941-8cmsl35nktdi3mbm410p0oqug39tfn7a.apps.googleusercontent.com',
    iosClientId: '216387410941-45gq9a26391lrnpliab4f3qe6l3llbvi.apps.googleusercontent.com',
    iosBundleId: 'com.pilach.app',
  );
}
